import { Player } from "./classes/Player";
import { StatsBar } from "./classes/StatsBar";
// import { Alien } from "./classes/Alien";
import { ManageAliens } from "./functions/manageAliens";
import { CollisonChecker } from "./functions/collisionChecker";
let player: Player;
export const Game = () => {
  console.log("start the game");
  // let alien = new Alien("img", 100);
  // alien.spawnAlien();
  // player.spawnPlayer();
  player = new Player();
  player.initialize();
  player.shooting();
  // let statsBar = new StatsBar(player);
  // statsBar.spawnStatsBar();
  ManageAliens();
  // CollisonChecker();
};
export { player };
